### ISSUE TITLE
SER 本地使用预训练模型预测 TypeError: _infer() got an unexpected keyword argument 'attention_masks'

### ISSUE THREAD

**Issue by Harryoung** [Harryoung/Test#33]
我们提供了issue bot来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide issue bot to solve issues, do you want it? (Please write yes/no):yes
> 请注意：issue bot基于大语言模型实现，其回答仅供参考。目前issue bot尚不能解析issue中的图片。/Please note: The issue bot is implemented based on large language models, and its answers are for reference only. Currently the issue bot cannot parse images in issues.

请在这里描述你的问题/Please describe your issue here:

Traceback (most recent call last):
File "E:\home\aistudio\PaddleOCR\tools\infer_vqa_token_ser.py", line 132, in 
result, _ = ser_engine(img_path)
File "E:\home\aistudio\PaddleOCR\tools\infer_vqa_token_ser.py", line 105, in call
post_result = self.post_process_class(
File "E:\home\aistudio\PaddleOCR\ppocr\postprocess\vqa_token_ser_layoutlm_postprocess.py", line 52, in call
return self._infer(preds, **kwargs)
TypeError: _infer() got an unexpected keyword argument 'attention_masks'

**Comment by fightfat** [comment]
@llm-issue-bot https://github.com/Harryoung/Test/issues/34
